package models

import "github.com/piupuer/go-helper/ms"

type AutoGenerated struct {
	Limit      int       `json:"limit"`
	Offset     int       `json:"offset"`
	Total      int       `json:"total"`
	Results    []Results `json:"results"`
	StatusCode int       `json:"statusCode"`
	Message    []Message `gorm:"foreignKey:MessageId" json:"message"`
}

type Message struct {
	ms.M
	Order            int    `json:"order"`
	Symbol           string `json:"symbol"`
	Name             string `json:"name"`
	ContractAddress  string `json:"contractAddress"`
	ImageURL         string `json:"imageUrl"`
	Price            string `json:"price"`
	Decimal          string `json:"decimal"`
	TokenDecimalNum  int    `json:"tokenDecimalNum"`
	AssetName        string `json:"assetName"`
	PercentChange24H string `json:"percent_change_24h"`
	Vsymbol          string `json:"vsymbol"`
}
